### PR TITLE
#27: Fixing GPU-enabled builds in GH Actions

### LINKED ISSUE #27: Linux GPU-enabled builds fail in Github Actions

### PR DESCRIPTION
**Pull request by roma-glushko**

### CODE REVIEW

**Comment by roma-glushko** [comment]
Hey @elezar, do you happen to know which docker should I use to get NVML binding build successfully? 
So far I have tried to use `nvidia/cuda:12.2.0-devel-ubuntu22.04` but still getting the following errors:

Screenshot 2023-10-08 at 14 41 51

Action Link: https://github.com/roma-glushko/resbeat/actions/runs/6447308047/job/17503427321

**Comment by elezar** [comment]
I've not seen an issue like this on Linux-based systems. What configuration is this action using?

**Comment by roma-glushko** [comment]
@elezar the config is pretty standard but I have changed the container image to use `nvidia/cuda` instead of the standard `ubuntu-latest`:
https://github.com/roma-glushko/resbeat/blob/5aaa30d032660339db625a806f6046e2207576d9/.github/workflows/release.yaml

But that was not really helpful 🤔

**Comment by elezar** [comment]
Note that your `.goreleaser` config seems to disable cgo: https://github.com/roma-glushko/resbeat/blame/279919cf983c028f3bae26978511056a1e7992e4/.goreleaser.yaml#L11

Could this be the issue here?

**Comment by roma-glushko** [comment]
@elezar thank you, Evan! That was definitely the right clue. What I have found was the issues (https://github.com/roma-glushko/resbeat/pull/28/files#diff-7326b55c062b0f46fe9e39aace0a25f4515cf206040fb91a6fd2cae839f5e826R9-R18):
- Needed to enable `CGO` 💹 
- Missed to pass `CGO_LDFLAGS_ALLOW` 💹 
- Had to limit the list of supported architectures to `amd64` only ✅ 

Once that was set, the binary was successfully compiled and could detect GPU in Kaggle env, for example:


Screenshot 2023-10-15 at 19 20 57

**Pull request merged**
